import Foundation

/// Compact argument descriptor used by generated code. Either a JSON-shaped
/// literal (pre-serialized by codegen) or a reference to a runtime variable.
public enum ArgDescriptor: Hashable, Sendable {
    case literal(JSONValue)
    case variable(String)
}

public extension PlanField {
    /// Factory used by code generated by `cachebay-cli`. Callers pass a
    /// compact (name, ArgDescriptor) list; this synthesises the concrete
    /// `buildArgs` / `stringifyArgs` closures so generated operations don't
    /// have to emit thousands of inline closure lines.
    ///
    /// Pre-computes `selId` (subtree fingerprint) from the same inputs the
    /// runtime compiler would use, so `CachePlan.id` stays stable whether the
    /// plan was parsed at runtime or built from a codegen'd literal.
    static func make(
        responseKey: String,
        fieldName: String,
        typeCondition: String? = nil,
        args: [(name: String, value: ArgDescriptor)] = [],
        isConnection: Bool = false,
        connectionKey: String? = nil,
        connectionFilters: [String]? = nil,
        connectionMode: ConnectionMode? = nil,
        pageArgs: [String]? = nil,
        skipIf: DirectiveCondition? = nil,
        includeIf: DirectiveCondition? = nil,
        children: [PlanField] = []
    ) -> PlanField {
        let expectedArgNames = args.map(\.name)
        let argTuples = args
        let (buildArgs, stringifyArgs) = Self.makeArgClosures(argTuples: argTuples)

        let selectionSet: [PlanField]? = children.isEmpty ? nil : children
        var selectionMap: [String: PlanField]? = nil
        if !children.isEmpty {
            var m: [String: PlanField] = [:]
            for c in children { m[c.responseKey] = c }
            selectionMap = m
        }

        // Fingerprint matches the runtime compiler's subtree fingerprint —
        // keeps plan.id identical whether compiled at runtime or codegen'd.
        let selId = Self.computeSelId(
            responseKey: responseKey,
            fieldName: fieldName,
            typeCondition: typeCondition,
            isConnection: isConnection,
            argNames: expectedArgNames,
            children: children
        )

        return PlanField(
            responseKey: responseKey,
            fieldName: fieldName,
            selectionSet: selectionSet,
            selectionMap: selectionMap,
            typeCondition: typeCondition,
            expectedArgNames: expectedArgNames,
            buildArgs: buildArgs,
            stringifyArgs: stringifyArgs,
            isConnection: isConnection,
            connectionKey: connectionKey,
            connectionFilters: connectionFilters,
            connectionMode: connectionMode,
            pageArgs: pageArgs,
            skipIf: skipIf,
            includeIf: includeIf,
            selId: selId
        )
    }

    // MARK: - Argument closure synthesis

    private static func makeArgClosures(
        argTuples: [(name: String, value: ArgDescriptor)]
    ) -> (@Sendable ([String: JSONValue]) -> [String: JSONValue], @Sendable ([String: JSONValue]) -> String) {
        if argTuples.isEmpty {
            return ({ _ in [:] }, { _ in "" })
        }
        let entries = argTuples
        let encodedKeys: [String] = entries.map { "\"\($0.name)\":" }

        let buildArgs: @Sendable ([String: JSONValue]) -> [String: JSONValue] = { variables in
            var out: [String: JSONValue] = [:]
            out.reserveCapacity(entries.count)
            for e in entries {
                let value: JSONValue
                switch e.value {
                case .literal(let v): value = v
                case .variable(let name):
                    guard let resolved = variables[name] else { continue }
                    value = resolved
                }
                if case .undefined = value { continue }
                out[e.name] = value
            }
            return out
        }
        let stringifyArgs: @Sendable ([String: JSONValue]) -> String = { variables in
            let args = buildArgs(variables)
            var parts: [String] = []
            parts.reserveCapacity(entries.count)
            for i in 0..<entries.count {
                if let v = args[entries[i].name] {
                    parts.append(encodedKeys[i] + stableStringify(v))
                }
            }
            return "{" + parts.joined(separator: ",") + "}"
        }
        return (buildArgs, stringifyArgs)
    }

    private static func computeSelId(
        responseKey: String,
        fieldName: String,
        typeCondition: String?,
        isConnection: Bool,
        argNames: [String],
        children: [PlanField]
    ) -> String {
        var parts: [String] = [responseKey, fieldName]
        if let tc = typeCondition { parts.append("@\(tc)") }
        if isConnection { parts.append("@connection") }
        if !argNames.isEmpty {
            parts.append("(\(argNames.sorted().joined(separator: ",")))")
        }
        if !children.isEmpty {
            let sorted = children.sorted { a, b in
                if a.responseKey != b.responseKey { return a.responseKey < b.responseKey }
                return a.fieldName < b.fieldName
            }
            parts.append("{\(sorted.map(\.selId).joined(separator: ","))}")
        }
        return parts.joined(separator: ":")
    }
}

public extension CachePlan {
    /// Factory used by code generated by `cachebay-cli`. The caller supplies
    /// the structural pieces (root, networkQuery, masks); this derives the
    /// stable `id` from the fingerprint so it matches the runtime compiler's.
    static func make(
        operation: OperationKind,
        rootTypename: String,
        root: [PlanField],
        networkQuery: String,
        strictVars: [String],
        canonicalVars: [String],
        windowArgs: Set<String>
    ) -> CachePlan {
        var rootSelectionMap: [String: PlanField] = [:]
        for f in root { rootSelectionMap[f.responseKey] = f }

        let fingerprint: String = {
            let sorted = root.sorted { a, b in
                if a.responseKey != b.responseKey { return a.responseKey < b.responseKey }
                return a.fieldName < b.fieldName
            }
            return "\(operation.rawValue):\(rootTypename):[\(sorted.map(\.selId).joined(separator: ","))]"
        }()
        let id = fnv1a32(fingerprint)

        return CachePlan(
            operation: operation,
            rootTypename: rootTypename,
            root: root,
            rootSelectionMap: rootSelectionMap,
            networkQuery: networkQuery,
            id: id,
            varMask: VarMask(strict: strictVars, canonical: canonicalVars),
            windowArgs: windowArgs,
            selectionFingerprint: fingerprint
        )
    }
}
