// Generated by cachebay-cli. DO NOT EDIT.
// Source: ElementQuery.graphql

import Foundation
import Cachebay

/// Query ElementQuery: ElementQuery.graphql
public struct ElementQuery: Cachebay.CachebayOperation {
    public struct Variables: Cachebay.OperationVariables {
        public var id: String
        public init(id: String) {
            self.id = id
        }
        public var __cachebay: [String: Cachebay.JSONValue] {
            var out: [String: Cachebay.JSONValue] = [:]
            out["id"] = .string(id)
            return out
        }
    }

    @CachebayData(typename: "")
    public struct Data: Sendable, Hashable, Cachebay.CachebayValue {
        public let node: ElementFields.Data?
    }

    public static let operationName: String = "ElementQuery"
    public static let networkQuery: String = """
query ElementQuery($id: ID!) {
  node(id: $id) {
  __typename 
    ...ElementFields
  }
}

fragment ElementFields on Element {
  __typename
  id
  derivatives {
    __typename
    id
    key
  }
  ... on VideoElement {
  __typename 
    url
  }
  ... on AudioElement {
  __typename 
    waveformURL
  }
}
"""

    /// SHA-256 of `networkQuery`, for Automatic Persisted Queries. Hashed at
    /// build time over the exact wire string; stable across builds.
    public static let persistedQueryHash: String = "77122085918ffc6b84613ce822ee2c758160eb58f51c5d50c43c2d3928ae493f"

    public static let cachePlan: CachePlan = CachePlan.make(
        operation: .query,
        rootTypename: "Query",
        root: [
            PlanField.make(
                responseKey: "node",
                fieldName: "node",
                args: [
                    (name: "id", value: .variable("id")),
                ],
                children: [
                    PlanField.make(
                        responseKey: "__typename",
                        fieldName: "__typename",
                        typeCondition: "Element",
                    ),
                    PlanField.make(
                        responseKey: "id",
                        fieldName: "id",
                        typeCondition: "Element",
                    ),
                    PlanField.make(
                        responseKey: "derivatives",
                        fieldName: "derivatives",
                        typeCondition: "Element",
                        children: [
                            PlanField.make(
                                responseKey: "__typename",
                                fieldName: "__typename",
                            ),
                            PlanField.make(
                                responseKey: "id",
                                fieldName: "id",
                            ),
                            PlanField.make(
                                responseKey: "key",
                                fieldName: "key",
                            ),
                        ]
                    ),
                    PlanField.make(
                        responseKey: "url",
                        fieldName: "url",
                        typeCondition: "VideoElement",
                    ),
                    PlanField.make(
                        responseKey: "waveformURL",
                        fieldName: "waveformURL",
                        typeCondition: "AudioElement",
                    ),
                ]
            ),
            PlanField.make(
                responseKey: "__typename",
                fieldName: "__typename",
            ),
        ],
        networkQuery: networkQuery,
        persistedHash: persistedQueryHash,
        strictVars: ["id"],
        canonicalVars: ["id"],
        windowArgs: Set([])
    )

    public static let document: QueryDocument = .plan(cachePlan)
}
