// Generated by cachebay-cli. DO NOT EDIT.
// Source: ElementQuery.graphql

import Foundation
import Cachebay

/// Fragment ElementFields: ElementQuery.graphql
public struct ElementFields: Cachebay.CachebayFragment {
    public typealias Variables = Cachebay.EmptyVariables

    @CachebayInterface
    public enum Data: Identifiable, Sendable, Hashable, Cachebay.CachebayValue {
        case audioElement(AudioElement)
        case videoElement(VideoElement)
        case unknown(Shared)

        @CachebayData(typename: "")
        public struct Shared: Identifiable, Sendable, Hashable, Codable, Cachebay.CachebayValue {
            public let __typename: String
            public let id: String
            public let derivatives: [Derivatives]
        }

        @CachebayData(typename: "Cook")
        public struct Derivatives: Identifiable, Sendable, Hashable, Codable, Cachebay.CachebayValue {
            public let __typename: String
            public let id: String
            public let key: String
        }

        @CachebayData(typename: "AudioElement")
        public struct AudioElement: Identifiable, Sendable, Hashable, Codable, Cachebay.CachebayValue {
            public let __typename: String
            public let id: String
            public let derivatives: [Derivatives]
            public let waveformURL: String
        }

        @CachebayData(typename: "VideoElement")
        public struct VideoElement: Identifiable, Sendable, Hashable, Codable, Cachebay.CachebayValue {
            public let __typename: String
            public let id: String
            public let derivatives: [Derivatives]
            public let url: String
        }
    }

    public static let operationName: String = "ElementFields"
    public static let networkQuery: String = """
fragment ElementFields on Element {
  __typename
  id
  derivatives {
    __typename
    id
    key
  }
  ... on VideoElement {
  __typename 
    url
  }
  ... on AudioElement {
  __typename 
    waveformURL
  }
}
"""

    /// SHA-256 of `networkQuery`, for Automatic Persisted Queries. Hashed at
    /// build time over the exact wire string; stable across builds.
    public static let persistedQueryHash: String = "c5ab4c229debe92119f4a2e3a12e9f23c797c0a724cd75cc880a524e5eb217f7"

    public static let cachePlan: CachePlan = CachePlan.make(
        operation: .fragment,
        rootTypename: "Element",
        root: [
            PlanField.make(
                responseKey: "__typename",
                fieldName: "__typename",
            ),
            PlanField.make(
                responseKey: "id",
                fieldName: "id",
            ),
            PlanField.make(
                responseKey: "derivatives",
                fieldName: "derivatives",
                children: [
                    PlanField.make(
                        responseKey: "__typename",
                        fieldName: "__typename",
                    ),
                    PlanField.make(
                        responseKey: "id",
                        fieldName: "id",
                    ),
                    PlanField.make(
                        responseKey: "key",
                        fieldName: "key",
                    ),
                ]
            ),
            PlanField.make(
                responseKey: "url",
                fieldName: "url",
                typeCondition: "VideoElement",
            ),
            PlanField.make(
                responseKey: "waveformURL",
                fieldName: "waveformURL",
                typeCondition: "AudioElement",
            ),
        ],
        networkQuery: networkQuery,
        persistedHash: persistedQueryHash,
        strictVars: [],
        canonicalVars: [],
        windowArgs: Set([])
    )

    public static let document: QueryDocument = .plan(cachePlan)
    public static let fragmentName: String = "ElementFields"
    public static let onTypename: String = "Element"
    public static var __cachebayFieldNames: [AnyKeyPath: String] { Data.__cachebayFieldNames }
}
