// Generated by cachebay-cli. DO NOT EDIT.

import Cachebay

public enum SpellKind: String, Codable, Sendable, CaseIterable {
    case charm = "CHARM"
    case hex = "HEX"
    case jinx = "JINX"
}

public enum SpellOrderBy: String, Codable, Sendable, CaseIterable {
    case name = "NAME"
    case power = "POWER"
}

public enum SpellTag: String, Codable, Sendable, CaseIterable {
    case offensive = "OFFENSIVE"
    case defensive = "DEFENSIVE"
    case utility = "UTILITY"
}

