// Generated by cachebay-cli. DO NOT EDIT.
// Source: SpellEnumDetail.graphql

import Foundation
import Cachebay

/// Query SpellEnumDetail: SpellEnumDetail.graphql
public struct SpellEnumDetail: Cachebay.CachebayOperation {
    public struct Variables: Cachebay.OperationVariables {
        public var id: String
        public var order: SpellOrderBy?
        public init(id: String, order: SpellOrderBy? = nil) {
            self.id = id
            self.order = order
        }
        public var __cachebay: [String: Cachebay.JSONValue] {
            var out: [String: Cachebay.JSONValue] = [:]
            out["id"] = .string(id)
            if let order = order { out["order"] = .string(order.rawValue) }
            return out
        }
    }

    @CachebayData(typename: "")
    public struct Data: Sendable, Hashable, Codable, Cachebay.CachebayValue {
        public let spell: Spell?

        @CachebayData(typename: "Spell")
        public struct Spell: Identifiable, Sendable, Hashable, Codable, Cachebay.CachebayValue {
            public let __typename: String
            public let id: String
            public let name: String
            public let kind: Cachebay.GraphQLEnum<SpellKind>
            public let mood: Cachebay.GraphQLEnum<SpellKind>?
            public let state: String
            public let tags: [Cachebay.GraphQLEnum<SpellTag>]
        }
    }

    public static let operationName: String = "SpellEnumDetail"
    public static let networkQuery: String = """
query SpellEnumDetail($id: ID!, $order: SpellOrderBy) {
  spell(id: $id, order: $order) {
    __typename
    id
    name
    kind
    mood
    state
    ...SpellTagBits
  }
}

fragment SpellTagBits on Spell {
  __typename 
  tags
}
"""

    /// SHA-256 of `networkQuery`, for Automatic Persisted Queries. Hashed at
    /// build time over the exact wire string; stable across builds.
    public static let persistedQueryHash: String = "9f4b6cd3d0bf4009700b091a3ec5843ae63ffc3ef917a212ea33c16c3a8e3962"

    public static let cachePlan: CachePlan = CachePlan.make(
        operation: .query,
        rootTypename: "Query",
        root: [
            PlanField.make(
                responseKey: "spell",
                fieldName: "spell",
                args: [
                    (name: "id", value: .variable("id")),
                    (name: "order", value: .variable("order")),
                ],
                children: [
                    PlanField.make(
                        responseKey: "__typename",
                        fieldName: "__typename",
                    ),
                    PlanField.make(
                        responseKey: "id",
                        fieldName: "id",
                    ),
                    PlanField.make(
                        responseKey: "name",
                        fieldName: "name",
                    ),
                    PlanField.make(
                        responseKey: "kind",
                        fieldName: "kind",
                    ),
                    PlanField.make(
                        responseKey: "mood",
                        fieldName: "mood",
                    ),
                    PlanField.make(
                        responseKey: "state",
                        fieldName: "state",
                    ),
                    PlanField.make(
                        responseKey: "tags",
                        fieldName: "tags",
                        typeCondition: "Spell",
                    ),
                ]
            ),
            PlanField.make(
                responseKey: "__typename",
                fieldName: "__typename",
            ),
        ],
        networkQuery: networkQuery,
        persistedHash: persistedQueryHash,
        strictVars: ["id", "order"],
        canonicalVars: ["id", "order"],
        windowArgs: Set([])
    )

    public static let document: QueryDocument = .plan(cachePlan)
}
