// Generated by cachebay-cli. DO NOT EDIT.
// Source: SpellDetail.graphql

import Cachebay

/// Query SpellDetail: SpellDetail.graphql
public struct SpellDetail: Cachebay.CachebayOperation {
    public struct Variables: Cachebay.OperationVariables {
        public var id: String
        public init(id: String) {
            self.id = id
        }
        public var __cachebay: [String: Cachebay.JSONValue] {
            var out: [String: Cachebay.JSONValue] = [:]
            out["id"] = .string(id)
            return out
        }
    }

    @CachebayData(typename: "")
    public struct Data: Sendable, Hashable, Cachebay.CachebayValue {
        public let spell: SpellFields.Data?
    }

    public static let operationName: String = "SpellDetail"
    public static let networkQuery: String = """
query SpellDetail($id: ID!) {
  spell(id: $id) {
  __typename 
    ...SpellFields
  }
}

fragment SpellFields on Spell {
  __typename 
  id
  name
  category
  creator
  effect
  light
  imageUrl
  wikiUrl
}
"""

    /// SHA-256 of `networkQuery`, for Automatic Persisted Queries. Hashed at
    /// build time over the exact wire string; stable across builds.
    public static let persistedQueryHash: String = "c5fa84c7d094a26fbbc98a3382c7ec4071600342cd24fd68482e92c54ea11291"

    public static let cachePlan: CachePlan = CachePlan.make(
        operation: .query,
        rootTypename: "Query",
        root: [
            PlanField.make(
                responseKey: "spell",
                fieldName: "spell",
                args: [
                    (name: "id", value: .variable("id")),
                ],
                children: [
                    PlanField.make(
                        responseKey: "id",
                        fieldName: "id",
                        typeCondition: "Spell",
                    ),
                    PlanField.make(
                        responseKey: "name",
                        fieldName: "name",
                        typeCondition: "Spell",
                    ),
                    PlanField.make(
                        responseKey: "category",
                        fieldName: "category",
                        typeCondition: "Spell",
                    ),
                    PlanField.make(
                        responseKey: "creator",
                        fieldName: "creator",
                        typeCondition: "Spell",
                    ),
                    PlanField.make(
                        responseKey: "effect",
                        fieldName: "effect",
                        typeCondition: "Spell",
                    ),
                    PlanField.make(
                        responseKey: "light",
                        fieldName: "light",
                        typeCondition: "Spell",
                    ),
                    PlanField.make(
                        responseKey: "imageUrl",
                        fieldName: "imageUrl",
                        typeCondition: "Spell",
                    ),
                    PlanField.make(
                        responseKey: "wikiUrl",
                        fieldName: "wikiUrl",
                        typeCondition: "Spell",
                    ),
                    PlanField.make(
                        responseKey: "__typename",
                        fieldName: "__typename",
                        typeCondition: "Spell",
                    ),
                ]
            ),
            PlanField.make(
                responseKey: "__typename",
                fieldName: "__typename",
            ),
        ],
        networkQuery: networkQuery,
        persistedHash: persistedQueryHash,
        strictVars: ["id"],
        canonicalVars: ["id"],
        windowArgs: Set([])
    )

    public static let document: QueryDocument = .plan(cachePlan)
}
