// Generated by cachebay-cli. DO NOT EDIT.
// Source: SpellDetail.graphql

import Cachebay

/// Fragment SpellFields: SpellDetail.graphql
public struct SpellFields: Cachebay.CachebayFragment {
    public typealias Variables = Cachebay.EmptyVariables

    @CachebayData(typename: "Spell")
    public struct Data: Identifiable, Sendable, Hashable, Cachebay.CachebayValue {
        public let id: String
        public let name: String
        public let category: String
        public let creator: String?
        public let effect: String
        public let light: String?
        public let imageUrl: String?
        public let wikiUrl: String?
        public let __typename: String
    }

    public static let operationName: String = "SpellFields"
    public static let networkQuery: String = """
fragment SpellFields on Spell {
  __typename 
  id
  name
  category
  creator
  effect
  light
  imageUrl
  wikiUrl
}
"""

    /// SHA-256 of `networkQuery`, for Automatic Persisted Queries. Hashed at
    /// build time over the exact wire string; stable across builds.
    public static let persistedQueryHash: String = "1843e3d0f062ddfec583c570f270f58d609531c03d3b07ac3a01f1ce5af34380"

    public static let cachePlan: CachePlan = CachePlan.make(
        operation: .fragment,
        rootTypename: "Spell",
        root: [
            PlanField.make(
                responseKey: "id",
                fieldName: "id",
            ),
            PlanField.make(
                responseKey: "name",
                fieldName: "name",
            ),
            PlanField.make(
                responseKey: "category",
                fieldName: "category",
            ),
            PlanField.make(
                responseKey: "creator",
                fieldName: "creator",
            ),
            PlanField.make(
                responseKey: "effect",
                fieldName: "effect",
            ),
            PlanField.make(
                responseKey: "light",
                fieldName: "light",
            ),
            PlanField.make(
                responseKey: "imageUrl",
                fieldName: "imageUrl",
            ),
            PlanField.make(
                responseKey: "wikiUrl",
                fieldName: "wikiUrl",
            ),
            PlanField.make(
                responseKey: "__typename",
                fieldName: "__typename",
            ),
        ],
        networkQuery: networkQuery,
        persistedHash: persistedQueryHash,
        strictVars: [],
        canonicalVars: [],
        windowArgs: Set([])
    )

    public static let document: QueryDocument = .plan(cachePlan)
    public static let fragmentName: String = "SpellFields"
    public static let onTypename: String = "Spell"
    public static var __cachebayFieldNames: [AnyKeyPath: String] { Data.__cachebayFieldNames }
}
