// Generated by cachebay-cli. DO NOT EDIT.
// Source: SpellEnumDetail.graphql

import Foundation
import Cachebay

/// Fragment SpellTagBits: SpellEnumDetail.graphql
public struct SpellTagBits: Cachebay.CachebayFragment {
    public typealias Variables = Cachebay.EmptyVariables

    @CachebayData(typename: "Spell")
    public struct Data: Sendable, Hashable, Cachebay.CachebayValue {
        public let tags: [Cachebay.GraphQLEnum<SpellTag>]
        public let __typename: String
    }

    public static let operationName: String = "SpellTagBits"
    public static let networkQuery: String = """
fragment SpellTagBits on Spell {
  __typename 
  tags
}
"""

    public static let cachePlan: CachePlan = CachePlan.make(
        operation: .fragment,
        rootTypename: "Spell",
        root: [
            PlanField.make(
                responseKey: "tags",
                fieldName: "tags",
            ),
            PlanField.make(
                responseKey: "__typename",
                fieldName: "__typename",
            ),
        ],
        networkQuery: networkQuery,
        strictVars: [],
        canonicalVars: [],
        windowArgs: Set([])
    )

    public static let document: QueryDocument = .plan(cachePlan)
    public static let fragmentName: String = "SpellTagBits"
    public static let onTypename: String = "Spell"
    public static var __cachebayFieldNames: [AnyKeyPath: String] { Data.__cachebayFieldNames }
}
