//! Swift emitter. Produces one file per operation/fragment plus a shared
//! `CachebayGenerated.swift` declaring the `Variables`/`Data` baselines.
//!
//! The generated code is deliberately minimal: typed `Variables` structs,
//! typed `Data` structs with thin accessors over the cache's materialized
//! `[String: Cachebay.JSONValue]`, and a pre-baked `CachePlan` constant per operation.
//!
//! Nothing exotic — no enum generation, no input-object generation in this MVP.
//! Those extend cleanly once the pipeline is proven.

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use crate::plan::{ArgPiece, ConnectionMode, OpKind, OutputShape, Plan, PlanField};
use crate::schema::{EnumTypeDef, InputField, InputTypeDef, TypeKind, TypeShape};

pub fn write_all(
    plans: &[Plan],
    inputs: &BTreeMap<String, InputTypeDef>,
    enums: &BTreeMap<String, EnumTypeDef>,
    interfaces: &BTreeMap<String, Vec<String>>,
    out_dir: &Path,
    module: &str,
) -> anyhow::Result<()> {
    if !enums.is_empty() {
        fs::write(out_dir.join("Enums.graphql.swift"), render_enums(enums))?;
    }
    if !inputs.is_empty() {
        fs::write(out_dir.join("Inputs.graphql.swift"), render_inputs(inputs))?;
    }
    fs::write(
        out_dir.join("Schema.graphql.swift"),
        render_schema(interfaces),
    )?;
    for plan in plans {
        let file_name = format!("{}.graphql.swift", plan.name);
        let contents = render_plan(plan, module);
        fs::write(out_dir.join(file_name), contents)?;
    }
    Ok(())
}

/// Schema-level constants the runtime reads at client construction.
/// Currently just the interface→implementers map (consumed by
/// `CachebayOptions.interfaces`); future schema-derived knobs (custom
/// scalar serialisers, type-policy keyFields, …) belong here too.
fn render_schema(interfaces: &BTreeMap<String, Vec<String>>) -> String {
    let mut s = String::new();
    s.push_str("// Generated by cachebay-cli. DO NOT EDIT.\n\n");
    s.push_str("import Cachebay\n\n");
    s.push_str("/// Generated schema metadata. Pass `CachebaySchema.interfaces`\n");
    s.push_str("/// to `CachebayOptions.interfaces` so the runtime knows which\n");
    s.push_str("/// concrete types implement which interfaces — required for\n");
    s.push_str("/// `fragment X on InterfaceName { ... }` to apply against the\n");
    s.push_str("/// concrete records when normalising/materialising.\n");
    s.push_str("public enum CachebaySchema {\n");
    if interfaces.is_empty() {
        // Swift parses `[]` as Array literal; the empty Dictionary
        // literal is `[:]`. Emit the dict form so consumers that have
        // no interfaces still get a valid `[String: [String]]` value.
        s.push_str("    public static let interfaces: [String: [String]] = [:]\n");
    } else {
        s.push_str("    public static let interfaces: [String: [String]] = [\n");
        for (iface, impls) in interfaces {
            let inner = impls
                .iter()
                .map(|n| format!("\"{}\"", n))
                .collect::<Vec<_>>()
                .join(", ");
            s.push_str(&format!("        \"{}\": [{}],\n", iface, inner));
        }
        s.push_str("    ]\n");
    }
    s.push_str("}\n");
    s
}

fn render_enums(enums: &BTreeMap<String, EnumTypeDef>) -> String {
    let mut s = String::new();
    s.push_str("// Generated by cachebay-cli. DO NOT EDIT.\n\n");
    s.push_str("import Cachebay\n\n");
    for (_, t) in enums {
        s.push_str(&format!("public enum {}: String, Sendable, CaseIterable {{\n", t.name));
        for v in &t.values {
            let ident = swift_identifier(&v.to_lowercased_camel());
            if ident == *v {
                s.push_str(&format!("    case {}\n", ident));
            } else {
                s.push_str(&format!("    case {} = \"{}\"\n", ident, v));
            }
        }
        s.push_str("}\n\n");
    }
    s
}

/// Trait-like helper on String to produce a Swift-friendly case name from an
/// enum value (e.g. `NAME_ASC` → `nameAsc`). We still emit `= "NAME_ASC"` so
/// server serialization is preserved.
trait EnumCaseName { fn to_lowercased_camel(&self) -> String; }
impl EnumCaseName for String {
    fn to_lowercased_camel(&self) -> String {
        let mut out = String::with_capacity(self.len());
        let mut upper_next = false;
        for (i, c) in self.chars().enumerate() {
            if c == '_' { upper_next = true; continue; }
            if i == 0 { out.push(c.to_ascii_lowercase()); }
            else if upper_next { out.push(c); upper_next = false; }
            else { out.push(c.to_ascii_lowercase()); }
        }
        out
    }
}

fn render_inputs(inputs: &BTreeMap<String, InputTypeDef>) -> String {
    let mut s = String::new();
    s.push_str("// Generated by cachebay-cli. DO NOT EDIT.\n\n");
    s.push_str("import Cachebay\n\n");
    for (_, t) in inputs {
        s.push_str(&format!("public struct {}: Sendable {{\n", t.name));
        for f in &t.fields {
            s.push_str(&format!("    public var {}: {}\n", swift_identifier(&f.name), swift_type_for_shape(&f.shape)));
        }
        // init
        s.push_str("    public init(");
        let args: Vec<String> = t
            .fields
            .iter()
            .map(|f| {
                let ty = swift_type_for_shape(&f.shape);
                let dflt = if f.shape.nullable { " = nil" } else { "" };
                format!("{}: {}{}", swift_identifier(&f.name), ty, dflt)
            })
            .collect();
        s.push_str(&args.join(", "));
        s.push_str(") {\n");
        for f in &t.fields {
            let ident = swift_identifier(&f.name);
            s.push_str(&format!("        self.{ident} = {ident}\n"));
        }
        s.push_str("    }\n");

        // __cachebay bridge
        s.push_str("    public var __cachebay: Cachebay.JSONValue {\n");
        if t.is_one_of {
            // `@oneOf` input objects: exactly one field must be present
            // in the wire payload, and the others MUST be omitted —
            // emitting them as `null` produces a server-side validation
            // error ("Field X must be non-null"). Every field on a
            // `@oneOf` input is nullable in the schema (the spec
            // requires it), so each carries an inner non-null value
            // we forward unmodified.
            s.push_str("        var out: [String: Cachebay.JSONValue] = [:]\n");
            for f in &t.fields {
                let ident = swift_identifier(&f.name);
                let inner_shape = TypeShape {
                    nullable: false,
                    ..f.shape.clone()
                };
                s.push_str(&format!(
                    "        if let {ident} = {ident} {{ out[\"{}\"] = {} }}\n",
                    f.name,
                    json_expr_for(&ident, &inner_shape)
                ));
            }
            s.push_str("        return .object(out)\n");
        } else {
            s.push_str("        var out: [String: Cachebay.JSONValue] = [:]\n");
            for f in &t.fields {
                let ident = swift_identifier(&f.name);
                s.push_str(&format!("        out[\"{}\"] = {}\n", f.name, json_expr_for(&ident, &f.shape)));
            }
            s.push_str("        return .object(out)\n");
        }
        s.push_str("    }\n");
        s.push_str("}\n\n");
    }
    s
}

/// Build the Cachebay.JSONValue expression that encodes a Swift binding of the given
/// shape. Handles nullability, list wrapping, input-object recursion, and
/// primitive scalars. Single source of truth used by both input-object
/// codecs and per-operation `Variables.__cachebay`.
fn json_expr_for(ident: &str, shape: &TypeShape) -> String {
    fn wrap_leaf(inner: &str, shape: &TypeShape) -> String {
        match shape.kind {
            TypeKind::Scalar => match shape.named.as_str() {
                "String" | "ID" => format!(".string({inner})"),
                "Int" => format!(".int(Int64({inner}))"),
                "Float" => format!(".double({inner})"),
                "Boolean" => format!(".bool({inner})"),
                _ => "Cachebay.JSONValue.null".into(),
            },
            TypeKind::CustomScalar => inner.to_string(),
            // Typed enum — bridge via rawValue; cachebay stores the server-side string.
            TypeKind::Enum => format!(".string({inner}.rawValue)"),
            TypeKind::InputObject => format!("({inner}).__cachebay"),
        }
    }

    if shape.list {
        let leaf_shape = TypeShape {
            nullable: shape.inner_nullable,
            list: false,
            ..shape.clone()
        };
        let item_expr = if leaf_shape.nullable {
            format!("{{ $0.map {{ {} }} ?? .null }}", wrap_leaf("$0", &leaf_shape))
        } else {
            format!("{{ {} }}", wrap_leaf("$0", &leaf_shape))
        };
        if shape.nullable {
            format!("({ident}).map {{ arr in Cachebay.JSONValue.array(arr.map {item_expr}) }} ?? .null")
        } else {
            format!("Cachebay.JSONValue.array({ident}.map {item_expr})")
        }
    } else if shape.nullable {
        format!("({ident}).map {{ {} }} ?? .null", wrap_leaf("$0", shape))
    } else {
        wrap_leaf(ident, shape)
    }
}

fn render_plan(plan: &Plan, _module: &str) -> String {
    let mut s = String::new();
    s.push_str("// Generated by cachebay-cli. DO NOT EDIT.\n");
    s.push_str(&format!("// Source: {}\n\n", plan.source_path));
    s.push_str("import Cachebay\n\n");

    let struct_kind = match plan.operation_kind {
        OpKind::Query => "Query",
        OpKind::Mutation => "Mutation",
        OpKind::Subscription => "Subscription",
        OpKind::Fragment => "Fragment",
    };

    s.push_str(&format!("/// {} {}: {}\n", struct_kind, plan.name, plan.source_path));
    // Q/M/S conform to `Cachebay.Operation`; fragments to `Cachebay.Fragment`.
    // Both protocols share the typed surface (`networkQuery`, `document`,
    // `Variables`, `Data`) so the typed overloads (`executeMutation<Op>`,
    // `readFragment<F>`, …) pick the right one up via overload resolution
    // on the protocol constraint.
    let is_operation = !matches!(plan.operation_kind, OpKind::Fragment);
    let is_fragment = matches!(plan.operation_kind, OpKind::Fragment);
    let conforms = if is_operation {
        ": Cachebay.Operation"
    } else {
        ": Cachebay.Fragment"
    };
    s.push_str(&format!("public struct {}{} {{\n", plan.name, conforms));

    // Variables — conforms to `OperationVariables` whether this is an
    // operation or a fragment (both protocols have an `associatedtype
    // Variables: OperationVariables`). With-variables structs get an
    // explicit struct; zero-variable structs alias to `EmptyVariables`
    // so typed overloads always have a valid `Variables` to construct
    // — caller writes `.init()` regardless of which side of the
    // op/fragment fence the operation lives on.
    if !plan.variables.is_empty() {
        let var_conforms = if is_operation || is_fragment {
            ": Cachebay.OperationVariables"
        } else {
            ": Sendable"
        };
        s.push_str(&format!("    public struct Variables{} {{\n", var_conforms));
        for v in &plan.variables {
            s.push_str(&format!("        public var {}: {}\n", swift_identifier(&v.name), v.swift_type));
        }
        s.push_str("        public init(");
        let args: Vec<String> = plan
            .variables
            .iter()
            .map(|v| {
                let ident = swift_identifier(&v.name);
                let dflt = if v.nullable { " = nil" } else { "" };
                format!("{}: {}{}", ident, v.swift_type, dflt)
            })
            .collect();
        s.push_str(&args.join(", "));
        s.push_str(") {\n");
        for v in &plan.variables {
            let ident = swift_identifier(&v.name);
            s.push_str(&format!("            self.{ident} = {ident}\n"));
        }
        s.push_str("        }\n");
        s.push_str("        public var __cachebay: [String: Cachebay.JSONValue] {\n");
        s.push_str("            var out: [String: Cachebay.JSONValue] = [:]\n");
        for v in &plan.variables {
            let ident = swift_identifier(&v.name);
            s.push_str(&format!("            out[\"{}\"] = {}\n", v.name, json_expr_for(&ident, &v.shape)));
        }
        s.push_str("            return out\n");
        s.push_str("        }\n");
        s.push_str("    }\n\n");
    } else if is_operation || is_fragment {
        s.push_str("    public typealias Variables = Cachebay.EmptyVariables\n\n");
    }

    // Data struct — partitioned by type condition so polymorphic roots emit
    // `asX: AsX?` downcasts exactly like nested selections. Every selection
    // struct (root + nested + polymorphic narrowings) conforms to
    // `Cachebay.OperationData`; the codegen already emits the required
    // `init(__data:)` and `var __data`, and uniform conformance lets typed
    // helpers like `prepend(node:)` accept any node shape.
    //
    // `extensions` collects connection helper extensions (`prepend(node:)`,
    // `remove(where:)`) that we need to emit at file scope — Swift won't
    // accept extensions nested inside another type body. The full type
    // path (e.g. `Projects.Data.Projects`) is threaded through so each
    // emitted extension targets the right nested struct.
    let mut extensions: Vec<String> = Vec::new();
    if !plan.root.is_empty() {
        let data_path = format!("{}.Data", plan.name);
        s.push_str(&render_selection_struct(
            "Data",
            &plan.root_typename,
            &plan.root,
            "    ",
            &data_path,
            &mut extensions,
        ));
        s.push_str("\n");
    }

    // The pre-baked CachePlan + network query + helpers used by the runtime.
    s.push_str("    public static let operationName: String = \"");
    s.push_str(&plan.name);
    s.push_str("\"\n");

    s.push_str("    public static let networkQuery: String = ");
    s.push_str(&render_string_literal(&plan.network_query));
    s.push_str("\n\n");

    // Pre-baked CachePlan literal — runtime skips the parse/dedupe/lower path
    // entirely; `plan.id` is derived from the same fingerprint the compiler
    // would have produced, so signatures match whether the plan was built
    // here or at runtime via `Compiler.compilePlan`.
    s.push_str("    public static let cachePlan: CachePlan = CachePlan.make(\n");
    s.push_str(&format!("        operation: {},\n", operation_kind_literal(plan.operation_kind)));
    s.push_str(&format!("        rootTypename: \"{}\",\n", plan.root_typename));
    s.push_str("        root: [\n");
    for f in &plan.root {
        s.push_str(&render_plan_field_literal(f, "            "));
    }
    s.push_str("        ],\n");
    s.push_str("        networkQuery: networkQuery,\n");
    s.push_str(&format!("        strictVars: {},\n", render_string_list(&plan_strict_vars(plan))));
    s.push_str(&format!("        canonicalVars: {},\n", render_string_list(&plan_canonical_vars(plan))));
    s.push_str(&format!("        windowArgs: Set({})\n", render_string_list(&collect_window_args(&plan.root))));
    s.push_str("    )\n\n");

    s.push_str("    public static let document: QueryDocument = .plan(cachePlan)\n");

    // Fragments expose `fragmentName` so the typed `readFragment<F>` /
    // `writeFragment<F>` overloads can disambiguate when a single
    // source string ships multiple fragment definitions, and
    // `onTypename` so the typed APIs can build the canonical cache key
    // from a bare entity id (`"\(onTypename):\(id)"`).
    if is_fragment {
        s.push_str(&format!("    public static let fragmentName: String = \"{}\"\n", plan.name));
        s.push_str(&format!("    public static let onTypename: String = \"{}\"\n", plan.root_typename));
    }

    s.push_str("}\n");

    // File-scope extensions: connection helpers for any nested struct
    // whose selection has a Relay-style `pageInfo` + `edges { node }`
    // shape. Emitted outside the operation struct because Swift forbids
    // extensions inside another type body.
    for ext in &extensions {
        s.push_str("\n");
        s.push_str(ext);
    }
    s
}

fn operation_kind_literal(kind: OpKind) -> &'static str {
    match kind {
        OpKind::Query => ".query",
        OpKind::Mutation => ".mutation",
        OpKind::Subscription => ".subscription",
        OpKind::Fragment => ".fragment",
    }
}

fn render_string_list(xs: &[String]) -> String {
    if xs.is_empty() { return "[]".into(); }
    let inner: Vec<String> = xs.iter().map(|s| format!("\"{}\"", s.replace('"', "\\\""))).collect();
    format!("[{}]", inner.join(", "))
}

fn plan_strict_vars(plan: &Plan) -> Vec<String> {
    let mut out = std::collections::BTreeSet::<String>::new();
    collect_strict_vars_from_fields(&plan.root, &mut out);
    out.into_iter().collect()
}

fn plan_canonical_vars(plan: &Plan) -> Vec<String> {
    let win: std::collections::BTreeSet<String> = collect_window_args(&plan.root).into_iter().collect();
    plan_strict_vars(plan).into_iter().filter(|v| !win.contains(v)).collect()
}

fn collect_strict_vars_from_fields(fields: &[PlanField], out: &mut std::collections::BTreeSet<String>) {
    for f in fields {
        for piece in &f.arg_template {
            if let crate::plan::ArgPiece::Variable(name) = piece { out.insert(name.clone()); }
        }
        collect_strict_vars_from_fields(&f.children, out);
    }
}

fn collect_window_args(fields: &[PlanField]) -> Vec<String> {
    let mut set = std::collections::BTreeSet::<String>::new();
    fn walk(fields: &[PlanField], set: &mut std::collections::BTreeSet<String>) {
        for f in fields {
            if f.is_connection {
                for a in &f.page_args { set.insert(a.clone()); }
            }
            walk(&f.children, set);
        }
    }
    walk(fields, &mut set);
    set.into_iter().collect()
}

fn render_plan_field_literal(f: &PlanField, indent: &str) -> String {
    let mut s = String::new();
    s.push_str(indent);
    s.push_str("PlanField.make(\n");
    s.push_str(&format!("{indent}    responseKey: \"{}\",\n", f.response_key));
    s.push_str(&format!("{indent}    fieldName: \"{}\",\n", f.field_name));
    if let Some(tc) = &f.type_condition {
        s.push_str(&format!("{indent}    typeCondition: \"{}\",\n", tc));
    }
    let args = split_arg_template(&f.arg_template);
    if !args.is_empty() {
        s.push_str(&format!("{indent}    args: [\n"));
        for arg in &args {
            s.push_str(&format!("{indent}        (name: \"{}\", value: {}),\n", arg.name, arg.swift_value));
        }
        s.push_str(&format!("{indent}    ],\n"));
    }
    if f.is_connection {
        s.push_str(&format!("{indent}    isConnection: true,\n"));
        if let Some(k) = &f.connection_key {
            s.push_str(&format!("{indent}    connectionKey: \"{}\",\n", k));
        }
        if !f.connection_filters.is_empty() {
            s.push_str(&format!("{indent}    connectionFilters: {},\n", render_string_list(&f.connection_filters)));
        }
        if let Some(mode) = f.connection_mode {
            let m = match mode {
                crate::plan::ConnectionMode::Infinite => ".infinite",
                crate::plan::ConnectionMode::Page => ".page",
            };
            s.push_str(&format!("{indent}    connectionMode: {},\n", m));
        }
        if !f.page_args.is_empty() {
            s.push_str(&format!("{indent}    pageArgs: {},\n", render_string_list(&f.page_args)));
        }
    }
    if !f.children.is_empty() {
        s.push_str(&format!("{indent}    children: [\n"));
        for child in &f.children {
            s.push_str(&render_plan_field_literal(child, &format!("{indent}        ")));
        }
        s.push_str(&format!("{indent}    ]\n"));
    }
    s.push_str(indent);
    s.push_str("),\n");
    s
}

struct SplitArg { name: String, swift_value: String }

/// Re-partition `arg_template` (which is already a flat stream of pieces used
/// to stringify args) back into individual `(name, value)` pairs so the
/// emitter can write one `.variable(...)` or `.literal(...)` entry each.
fn split_arg_template(template: &[ArgPiece]) -> Vec<SplitArg> {
    let mut out: Vec<SplitArg> = Vec::new();
    let mut i = 0;
    while i < template.len() {
        // Expect a Raw("\"name\":") marker to introduce each arg.
        let Some(ArgPiece::Raw(name_raw)) = template.get(i) else { i += 1; continue; };
        if !(name_raw.starts_with('"') && name_raw.ends_with(':')) { i += 1; continue; }
        let name = name_raw.trim_start_matches('"').trim_end_matches(":").trim_end_matches('"').to_string();
        i += 1;
        // Collect tokens up to the next Raw(",") or Raw("\"name\":") or end.
        let mut tokens: Vec<&ArgPiece> = Vec::new();
        while i < template.len() {
            match &template[i] {
                ArgPiece::Raw(s) if s == "," => { i += 1; break; }
                ArgPiece::Raw(s) if s.starts_with('"') && s.ends_with(':') => break,
                piece => { tokens.push(piece); i += 1; }
            }
        }
        out.push(SplitArg { name, swift_value: render_arg_value(&tokens) });
    }
    out
}

fn render_arg_value(tokens: &[&ArgPiece]) -> String {
    if tokens.len() == 1 {
        match tokens[0] {
            ArgPiece::Variable(name) => return format!(".variable(\"{name}\")"),
            ArgPiece::Literal(json) => return format!(".literal({})", json_literal_to_swift(json)),
            ArgPiece::Raw(_) => return ".literal(.null)".into(),
        }
    }
    // Composite literal (list or object) — reconstruct the raw JSON fragment
    // and fall back to runtime-parse via a helper on `Cachebay.JSONValue`.
    let mut frag = String::new();
    for t in tokens {
        match t {
            ArgPiece::Literal(s) => frag.push_str(s),
            ArgPiece::Variable(name) => frag.push_str(&format!("\"${}\"", name)),
            ArgPiece::Raw(s) => frag.push_str(s),
        }
    }
    format!(".literal(Cachebay.JSONValue.parseLiteral({:?}))", frag)
}

fn json_literal_to_swift(json: &str) -> String {
    if json == "null" { return ".null".into(); }
    if json == "true" { return ".bool(true)".into(); }
    if json == "false" { return ".bool(false)".into(); }
    if let Some(stripped) = json.strip_prefix('"').and_then(|s| s.strip_suffix('"')) {
        return format!(".string({:?})", stripped);
    }
    if let Ok(i) = json.parse::<i64>() { return format!(".int({})", i); }
    if let Ok(d) = json.parse::<f64>() { return format!(".double({})", d); }
    format!("Cachebay.JSONValue.parseLiteral({:?})", json)
}

fn render_string_literal(s: &str) -> String {
    // Swift """ multi-line literal.
    format!("\"\"\"\n{}\n\"\"\"", s)
}

fn render_field_accessor(f: &PlanField, indent: &str) -> String {
    let mut s = String::new();
    let rk = &f.response_key;
    let swift_name = swift_identifier(rk);
    let type_str = swift_type_for_field(f);

    // Every accessor is `get`/`set`. Setters are required for the typed
    // optimistic-patch closure pattern to work — `b.patch(fragment:F.self,
    // target:) { draft in draft.title = "x" }` builds the patch by
    // assigning into `draft`, and only fields the closure touches end
    // up in `__data` (so the patch stays minimal). Without setters the
    // closure couldn't write at all, and the user would be back to
    // hand-rolled `[String: JSONValue]` literals.
    s.push_str(&format!("{indent}public var {swift_name}: {type_str} {{\n"));
    s.push_str(&format!("{indent}    get {{ {} }}\n", read_expr_for_field(f, "__data", rk)));
    s.push_str(&format!("{indent}    set {{ __data[\"{rk}\"] = {} }}\n", write_expr_for_field(f, "newValue")));
    s.push_str(&format!("{indent}}}\n"));
    s
}

/// Build the `JSONValue` expression that round-trips a typed `newValue`
/// back into the underlying `__data` dict for the setter. Mirrors
/// `read_expr_for_field` in reverse — both shapes (object + leaf) and
/// both modes (single + list) are covered so the setter works for any
/// typed field on a generated selection struct.
fn write_expr_for_field(f: &PlanField, value: &str) -> String {
    match &f.output_shape {
        OutputShape::Object { nullable, list } => {
            if *list {
                if *nullable {
                    format!("({value}).map {{ arr in Cachebay.JSONValue.array(arr.map {{ Cachebay.JSONValue.object($0.__data) }}) }} ?? .null")
                } else {
                    format!("Cachebay.JSONValue.array(({value}).map {{ Cachebay.JSONValue.object($0.__data) }})")
                }
            } else if *nullable {
                format!("({value}).map {{ Cachebay.JSONValue.object($0.__data) }} ?? .null")
            } else {
                format!("Cachebay.JSONValue.object(({value}).__data)")
            }
        }
        OutputShape::Leaf { nullable, list } => {
            let scalar_wrap = leaf_scalar_write_wrap(&f.named_type);
            if *list {
                if is_builtin_scalar(&f.named_type) {
                    if *nullable {
                        format!("({value}).map {{ arr in Cachebay.JSONValue.array(arr.map {{ {} }}) }} ?? .null", scalar_wrap.replace("$0", "$0"))
                    } else {
                        format!("Cachebay.JSONValue.array(({value}).map {{ {} }})", scalar_wrap.replace("$0", "$0"))
                    }
                } else {
                    // Custom-scalar list (JSONValue passthrough).
                    if *nullable {
                        format!("({value}).map {{ Cachebay.JSONValue.array($0) }} ?? .null")
                    } else {
                        format!("Cachebay.JSONValue.array({value})")
                    }
                }
            } else if *nullable {
                if is_builtin_scalar(&f.named_type) {
                    format!("({value}).map {{ {} }} ?? .null", scalar_wrap.replace("$0", "$0"))
                } else {
                    // Custom scalar nullable — `JSONValue?` -> use as-is or null.
                    format!("({value}) ?? .null")
                }
            } else {
                if is_builtin_scalar(&f.named_type) {
                    scalar_wrap.replace("$0", value)
                } else {
                    // Custom scalar non-null — JSONValue passthrough.
                    value.to_string()
                }
            }
        }
    }
}

/// Wrap a Swift scalar binding into a `Cachebay.JSONValue`. The placeholder
/// is `$0`; consumers `replace("$0", actual)` to specialise. Used by both
/// the leaf setter codegen and (in spirit) the leaf list element wrap.
fn leaf_scalar_write_wrap(named: &str) -> String {
    match named {
        "String" | "ID" => "Cachebay.JSONValue.string($0)".into(),
        "Int" => "Cachebay.JSONValue.int(Int64($0))".into(),
        "Float" => "Cachebay.JSONValue.double($0)".into(),
        "Boolean" => "Cachebay.JSONValue.bool($0)".into(),
        // Custom scalar — the typed accessor surfaces `JSONValue`, so
        // pass it through unchanged.
        _ => "$0".into(),
    }
}

fn read_expr_for_field(f: &PlanField, container: &str, key: &str) -> String {
    match &f.output_shape {
        OutputShape::Leaf { nullable, list } => {
            if *list {
                if is_builtin_scalar(&f.named_type) {
                    let body = primitive_extract_compactmap(&f.named_type);
                    let base = format!("({container}[\"{key}\"]?.array)?.compactMap {{ {body} }}");
                    if *nullable { base } else { format!("{} ?? []", base) }
                } else {
                    // Custom scalars (e.g. JSON) stay as `[JSONValue]` — no
                    // extraction, the elements are already the right type.
                    let base = format!("{container}[\"{key}\"]?.array");
                    if *nullable { base } else { format!("{} ?? []", base) }
                }
            } else {
                primitive_read(&f.named_type, container, key, *nullable)
            }
        }
        OutputShape::Object { nullable, list } => {
            let nested_type = nested_type_name(f);
            if *list {
                let base = format!("({container}[\"{key}\"]?.array)?.compactMap {{ if case .object(let o) = $0 {{ return {nested_type}(__data: o) }} else {{ return nil }} }}");
                if *nullable { base } else { format!("({base}) ?? []") }
            } else {
                let base = format!("({container}[\"{key}\"]?.object).map {{ {nested_type}(__data: $0) }}");
                if *nullable { base } else { format!("({base})!") }
            }
        }
    }
}

fn primitive_read(named: &str, container: &str, key: &str, nullable: bool) -> String {
    // Builtin scalars use the typed JSONValue accessor (`.string`, `.int`, …)
    // which already coerces. Custom scalars stay as `Cachebay.JSONValue` —
    // there's no narrower Swift type to extract them as, and `.object` would
    // produce `[String: JSONValue]` which mismatches the declared field type.
    let accessor: Option<&'static str> = match named {
        "String" | "ID" => Some(".string"),
        "Int" => Some(".int.map(Int.init)"),
        "Float" => Some(".double"),
        "Boolean" => Some(".bool"),
        _ => None,
    };
    let base = match accessor {
        Some(a) => format!("{container}[\"{key}\"]?{}", a),
        None => format!("{container}[\"{key}\"]"),
    };
    if nullable {
        base
    } else {
        // Required scalars get a safe default rather than force-unwrap.
        // The materialiser can hand back a partially-resolved row (e.g.
        // an unresolved `.ref(...)` or a polymorphic-only field accessed
        // from the wrong subtype variant), and crashing the consumer
        // is strictly worse than handing them a sentinel they can
        // detect (`id.isEmpty`, `count == 0`, etc.). Schema-required
        // fields should never be missing in well-formed cache data;
        // when they are, that's a bug to log, not a process abort.
        let default = match named {
            "String" | "ID" => "\"\"".to_string(),
            "Int" => "0".to_string(),
            "Float" => "0.0".to_string(),
            "Boolean" => "false".to_string(),
            _ => "Cachebay.JSONValue.null".to_string(),
        };
        format!("({}) ?? {}", base, default)
    }
}

fn is_builtin_scalar(named: &str) -> bool {
    matches!(named, "String" | "ID" | "Int" | "Float" | "Boolean")
}

fn primitive_extract_compactmap(named: &str) -> String {
    match named {
        "String" | "ID" => "if case .string(let v) = $0 { return v } else { return nil }".into(),
        "Int" => "if case .int(let v) = $0 { return Int(v) } else { return nil }".into(),
        "Float" => "if case .double(let v) = $0 { return v } else { return nil }".into(),
        "Boolean" => "if case .bool(let v) = $0 { return v } else { return nil }".into(),
        _ => "return $0".into(),
    }
}

fn leaf_primitive_swift(named: &str) -> &'static str {
    match named {
        "String" | "ID" => "String",
        "Int" => "Int",
        "Float" => "Double",
        "Boolean" => "Bool",
        _ => "Cachebay.JSONValue",
    }
}

/// Compute the nested Swift type name for an object field. When the
/// field's selection set is a pure fragment spread (`reuse_fragment`
/// set), we reference the fragment's already-emitted `Data` type
/// directly — collapsing per-position duplicate structs across queries
/// that spread the same fragment.
fn nested_type_name(f: &PlanField) -> String {
    match &f.reuse_fragment {
        Some(frag) => format!("{frag}.Data"),
        None => title_case(&f.response_key),
    }
}

fn swift_type_for_field(f: &PlanField) -> String {
    match &f.output_shape {
        OutputShape::Leaf { nullable, list } => {
            let leaf = leaf_primitive_swift(&f.named_type);
            let list_ty = if *list { format!("[{leaf}]") } else { leaf.to_string() };
            if *nullable { format!("{list_ty}?") } else { list_ty }
        }
        OutputShape::Object { nullable, list } => {
            let nested = nested_type_name(f);
            let list_ty = if *list { format!("[{nested}]") } else { nested };
            if *nullable { format!("{list_ty}?") } else { list_ty }
        }
    }
}

fn render_nested_type(
    f: &PlanField,
    indent: &str,
    type_path: &str,
    extensions: &mut Vec<String>,
) -> String {
    let name = title_case(&f.response_key);
    let nested_path = format!("{type_path}.{name}");
    render_selection_struct(&name, &f.named_type, &f.children, indent, &nested_path, extensions)
}

/// Partition children into "shared" (no type condition, or condition equal to
/// the parent selection type) and "per-type-case" groups (each condition that
/// narrows the parent). Used for both interface/union polymorphism and for
/// fragment spreads on the same type (which degenerate to shared).
fn partition_children<'a>(parent_named_type: &str, children: &'a [PlanField]) -> (Vec<&'a PlanField>, BTreeMap<String, Vec<&'a PlanField>>) {
    let mut shared: Vec<&PlanField> = Vec::new();
    let mut by_condition: BTreeMap<String, Vec<&PlanField>> = BTreeMap::new();
    for child in children {
        match &child.type_condition {
            None => shared.push(child),
            Some(tc) if tc == parent_named_type || parent_named_type.is_empty() => shared.push(child),
            Some(tc) => by_condition.entry(tc.clone()).or_default().push(child),
        }
    }
    (shared, by_condition)
}

/// Emit a typed selection struct — possibly with `asX: AsX?` accessors when
/// the children include inline-fragment type conditions that narrow `parent_named_type`.
/// Every selection struct conforms to `Cachebay.OperationData` so the typed
/// runtime helpers (`updateQuery`, `prepend(node:)`, …) can manipulate any
/// nested shape uniformly.
///
/// `type_path` is the full Swift dotted path to this struct from file scope
/// (e.g. `"Projects.Data.Projects"`); it's used when emitting connection
/// helper extensions for nested children, since extensions can't live
/// inside another type body. `extensions` is the shared collector — each
/// connection-shaped nested type pushes its file-scope extension here,
/// and `render_plan` flushes them after the operation struct.
fn render_selection_struct(
    swift_name: &str,
    parent_named_type: &str,
    children: &[PlanField],
    indent: &str,
    type_path: &str,
    extensions: &mut Vec<String>,
) -> String {
    let (shared, by_condition) = partition_children(parent_named_type, children);

    // Emit `: Cachebay.ConnectionEdge` on Relay-style edge structs — any
    // generated struct that has a `node: Node?` shared child of object
    // shape. This enables the `Sequence.nodes(as:)` sugar so consumers
    // can replace `edges?.compactMap { $0.node?.as(F.self) } ?? []`
    // with `edges.nodes(as: F.self)`. The protocol is purely a marker
    // (its sole requirement, `var node: Node?`, the codegen already
    // emits), so the conformance is structurally always satisfiable
    // here.
    let conforms_connection_edge = shared.iter().any(|c| {
        c.response_key == "node"
            && matches!(
                c.output_shape,
                OutputShape::Object { nullable: true, list: false }
            )
    });
    let conformances = if conforms_connection_edge {
        "Cachebay.OperationData, Cachebay.ConnectionEdge"
    } else {
        "Cachebay.OperationData"
    };

    let mut s = String::new();
    s.push_str(&format!("{indent}public struct {swift_name}: {conformances} {{\n"));
    s.push_str(&format!("{indent}    public var __data: [String: Cachebay.JSONValue]\n"));
    s.push_str(&format!("{indent}    public init(__data: [String: Cachebay.JSONValue]) {{ self.__data = __data }}\n"));

    // Shared accessors.
    for child in &shared {
        s.push_str(&render_field_accessor(child, &format!("{indent}    ")));
    }

    // Type-case downcasts: `var asDog: AsDog? { __typename == "Dog" ? ... : nil }`.
    for (tc, _) in &by_condition {
        let as_name = format!("As{}", tc);
        let ident = format!("as{}", tc);
        s.push_str(&format!("{indent}    public var {ident}: {as_name}? {{\n"));
        s.push_str(&format!("{indent}        guard __data[\"__typename\"]?.string == \"{tc}\" else {{ return nil }}\n"));
        s.push_str(&format!("{indent}        return {as_name}(__data: __data)\n"));
        s.push_str(&format!("{indent}    }}\n"));
    }

    // Nested selection types for shared children. Skip pure-fragment-
    // spread positions — their type is the fragment's already-emitted
    // `<FragmentName>.Data`, no duplicate nested struct here.
    for child in &shared {
        if !child.children.is_empty() && child.reuse_fragment.is_none() {
            s.push_str(&render_nested_type(child, &format!("{indent}    "), type_path, extensions));
        }
    }

    // Per-type-case structs. Each `AsX` re-exposes shared fields (they always
    // apply) plus the case-specific fields.
    for (tc, fields) in &by_condition {
        let as_name = format!("As{tc}");
        let as_path = format!("{type_path}.{as_name}");
        s.push_str(&format!("{indent}    public struct {as_name}: Cachebay.OperationData {{\n"));
        s.push_str(&format!("{indent}        public var __data: [String: Cachebay.JSONValue]\n"));
        s.push_str(&format!("{indent}        public init(__data: [String: Cachebay.JSONValue]) {{ self.__data = __data }}\n"));
        for shared_child in &shared {
            s.push_str(&render_field_accessor(shared_child, &format!("{indent}        ")));
        }
        for field in fields {
            s.push_str(&render_field_accessor(field, &format!("{indent}        ")));
        }
        for shared_child in &shared {
            if !shared_child.children.is_empty() && shared_child.reuse_fragment.is_none() {
                s.push_str(&render_nested_type(shared_child, &format!("{indent}        "), &as_path, extensions));
            }
        }
        for field in fields {
            if !field.children.is_empty() && field.reuse_fragment.is_none() {
                s.push_str(&render_nested_type(field, &format!("{indent}        "), &as_path, extensions));
            }
        }
        // AsX factory mirrors the parent's per-subtype factory — same
        // signature, returns `AsX` instead of the parent struct. Use
        // when the caller already has an `AsX` in hand and wants to
        // construct a sibling. Inside `AsX`, all nested types are
        // direct siblings, so no qualifier is needed.
        let mut as_factory_fields: Vec<(&PlanField, bool)> = shared.iter().map(|f| (*f, false)).collect();
        as_factory_fields.extend(fields.iter().map(|f| (*f, true)));
        s.push_str(&render_factory(
            &as_name,
            "make",
            tc,
            &as_factory_fields,
            None,
            &format!("{indent}        "),
        ));
        s.push_str(&format!("{indent}    }}\n"));
    }

    // Compile-time-safe constructors. Polymorphic structs get one
    // factory per type-condition (`Data.videoElement(...)`); plain
    // structs get a single `make` factory using the parent named
    // type as `__typename`. Codegen ALWAYS emits these — the price
    // is a few dozen lines per struct, the value is that forgetting
    // a selected field becomes a compile error rather than the
    // v0.4.0 silent-watcher-silence at runtime.
    if !by_condition.is_empty() {
        // At parent scope, subtype-specific nested types live ONLY
        // inside their `AsX` — qualify them with `AsX.` so the type
        // resolves. Shared nested types live as siblings on the
        // parent and need no qualifier.
        for (tc, fields) in &by_condition {
            let factory_name = lower_camel_case(tc);
            let qualifier = format!("As{tc}");
            let mut all_fields: Vec<(&PlanField, bool)> = shared.iter().map(|f| (*f, false)).collect();
            all_fields.extend(fields.iter().map(|f| (*f, true)));
            s.push_str(&render_factory(
                swift_name,
                &factory_name,
                tc,
                &all_fields,
                Some(&qualifier),
                &format!("{indent}    "),
            ));
        }
    } else if !parent_named_type.is_empty() {
        // Non-polymorphic — single `make` factory. Use a stable
        // generic name rather than `lower_camel_case(parent_named_type)`
        // because the latter collides with subtype factory names when
        // a fragment on a concrete type happens to share a name with
        // a polymorphic sibling's branch.
        let factory_fields: Vec<(&PlanField, bool)> = shared.iter().map(|f| (*f, false)).collect();
        s.push_str(&render_factory(
            swift_name,
            "make",
            parent_named_type,
            &factory_fields,
            None,
            &format!("{indent}    "),
        ));
    }

    s.push_str(&format!("{indent}}}\n"));
    s
}

/// Lowercase the first character. `"VideoElement"` → `"videoElement"`.
/// Used for factory method names — Swift convention is camelCase for
/// methods, so a `... on VideoElement { … }` branch becomes
/// `Data.videoElement(…)` factory.
fn lower_camel_case(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_lowercase().chain(chars).collect(),
        None => String::new(),
    }
}

/// Emit a static factory method on the surrounding struct that returns
/// a fully-shaped instance for `typename`. Every selected non-null
/// field becomes a required named parameter; nullable selections get
/// `= nil` defaults; `__typename` is hardcoded into the dict body so
/// callers never thread a typename string. The factory's return type
/// is the parent struct (`swift_name`) — calling
/// `MyFragment.Data.subtype(…)` yields a `Data`.
///
/// Compile-time safety: forgetting a required field is a compile error
/// at the call site, replacing the v0.4.0 silent-silence failure mode
/// where a missing selection-set field would silence a watcher at
/// runtime.
/// Build the Swift type expression for a factory parameter. For nested
/// object types, optionally qualify with a parent-struct prefix — used
/// when emitting a per-subtype factory at the parent scope, where the
/// subtype's own `MusicHighlights` nested struct lives only inside
/// `AsX` and needs `AsX.MusicHighlights` to resolve.
fn factory_param_type(f: &PlanField, qualify_prefix: Option<&str>) -> String {
    match &f.output_shape {
        OutputShape::Object { nullable, list } => {
            // Reuse-fragment positions take the fragment's already-
            // emitted `Data` type — same regardless of whether the
            // field lives at parent or `AsX` scope, so no qualifier
            // needed (the fragment lives at module scope).
            let nested = if f.reuse_fragment.is_some() {
                nested_type_name(f)
            } else {
                let raw = title_case(&f.response_key);
                match qualify_prefix {
                    Some(prefix) => format!("{prefix}.{raw}"),
                    None => raw,
                }
            };
            let list_ty = if *list { format!("[{nested}]") } else { nested };
            if *nullable { format!("{list_ty}?") } else { list_ty }
        }
        OutputShape::Leaf { .. } => swift_type_for_field(f),
    }
}

fn render_factory(
    swift_name: &str,
    factory_name: &str,
    typename: &str,
    fields: &[(&PlanField, bool)],
    subtype_qualifier: Option<&str>,
    indent: &str,
) -> String {
    let mut s = String::new();
    let non_typename: Vec<&(&PlanField, bool)> = fields.iter()
        .filter(|(f, _)| f.response_key != "__typename")
        .collect();
    s.push_str(&format!("{indent}public static func {factory_name}(\n"));
    for (i, (f, is_subtype)) in non_typename.iter().enumerate() {
        let name = swift_identifier(&f.response_key);
        let ty = if *is_subtype {
            factory_param_type(f, subtype_qualifier)
        } else {
            factory_param_type(f, None)
        };
        let is_optional = matches!(
            f.output_shape,
            OutputShape::Leaf { nullable: true, .. } | OutputShape::Object { nullable: true, .. }
        );
        let default = if is_optional { " = nil" } else { "" };
        let comma = if i + 1 < non_typename.len() { "," } else { "" };
        s.push_str(&format!("{indent}    {name}: {ty}{default}{comma}\n"));
    }
    s.push_str(&format!("{indent}) -> {swift_name} {{\n"));
    s.push_str(&format!("{indent}    {swift_name}(__data: [\n"));
    s.push_str(&format!("{indent}        \"__typename\": Cachebay.JSONValue.string(\"{typename}\"),\n"));
    for (f, _) in &non_typename {
        let name = swift_identifier(&f.response_key);
        let value = write_expr_for_field(f, &name);
        s.push_str(&format!("{indent}        \"{}\": {},\n", f.response_key, value));
    }
    s.push_str(&format!("{indent}    ])\n"));
    s.push_str(&format!("{indent}}}\n"));
    s
}

fn title_case(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_uppercase().chain(chars).collect(),
        None => String::new(),
    }
}

fn swift_identifier(s: &str) -> String {
    // Strip/replace anything Swift won't accept. GraphQL field names are already
    // `[_A-Za-z][_0-9A-Za-z]*`, so leading-digit is the only real concern, and
    // responseKey = alias ?? name means the emitter output tracks the source.
    match s {
        "class" | "struct" | "enum" | "protocol" | "extension" | "func" | "var" | "let"
        | "if" | "else" | "return" | "for" | "while" | "do" | "try" | "catch" | "throw"
        | "switch" | "case" | "default" | "self" | "init" | "deinit" => format!("`{s}`"),
        _ => s.to_string(),
    }
}

fn swift_type_for_shape(shape: &TypeShape) -> String {
    crate::plan::swift_type_for_shape(shape)
}

// Keep the public symbols used by main.rs reachable.
#[allow(dead_code)]
pub(crate) fn _suppress_unused_warnings(
    _c: ConnectionMode,
    _a: ArgPiece,
) {}
